---
- name: Install nfs-utils
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    - nfs-utils

- name: Creates directory
  file:
    path: /var/nfsshare/
    state: directory
    mode: 0766

- name: Copy /etc/exports configuration 
  template:
    src: exports.j2
    dest: /etc/exports
  notify: restart nfs


- name: Make sure if services are running
  systemd: 
    name: "{{ item }}" 
    enabled: yes
    state: started 
  with_items:
    - rpcbind
    - nfs-server
    - nfs-lock
    - nfs-idmap
