---

- name: Execute a replication controller configuration.
  include_tasks: rc.yml
  tags: 
    - rc

- name: Execute a service configuration.
  include_tasks: svc.yml
  tags:
    - svc 

- name: Execute pods scaling.
  include_tasks: po.yml
  tags:
    - po 


