---

- name: Execute a Persistent Volume configuration.
  include_tasks: pv.yml
  tags:
    - nginx 
    - pv

- name: Execute a Persistent Volume Claim configuration.
  include_tasks: pvc.yml
  tags:
    - nginx 
    - pvc

- name: Execute a replication controller configuration.
  include_tasks: rc.yml
  tags:
    - nginx 
    - rc

- name: Execute a service configuration.
  include_tasks: svc.yml
  tags:
    - nginx 
    - svc 

- name: Execute pods scaling.
  include_tasks: po.yml
  tags:
    - nginx 
    - po 


