--- 

- name: Check if a directory exists.
  file:
    path: /etc/kubernetes/rc
    state: directory
  register: rc_directory_checked

- name: Copy a nginx-rc template file.
  when: rc_directory_checked|succeeded
  template:
    src: nginx-rc.yml
    dest: /etc/kubernetes/rc/nginx-rc.yml
  register: rc_file_copied

- hame: Execute the rc configuration.
  when: rc_file_copied|succeeded
  shell: kubectl apply -f /etc/kubernetes/rc/nginx-rc.yml
