---

- name: Check if a directory exists.
  file:
    path: /etc/kubernetes/svc
    state: directory
  register: svc_directory_checked

- name: Copy a nginx-svc template file.
  when: svc_directory_checked|succeeded
  template:
    src: nginx-svc.yml
    dest: /etc/kubernetes/svc/nginx-svc.yml
  register: svc_file_copied

- hame: Execute the svc configuration.  
  when: svc_file_copied|succeeded
  shell: kubectl apply -f /etc/kubernetes/svc/nginx-svc.yml
