---
#---------------------------------------------------------------
- name: Creating registry
  docker:
    insecure_registry: true
    image: docker.io/registry:2
    restart_policy: always
    state: reloaded
    pull: always
    ports:
      - 0.0.0.0:5000:5000/tcp
    env:
        REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
        "/nfsshare/registry:/var/lib/registry"

