---

- name: Install Haproxy packages.
  include_tasks: pkg.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version > '6'

- name: Copy the haproxy.cfg config file.
  template:
    src: "haproxy.cfg.j2"
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy 
  tags:
    - haproxy
    - configure

