---

- name: Install kubernetes master node.
  hosts: master
  gather_facts: true
  sudo: yes
  roles:
    - kubernetes/master 
  tags: 
    - master

- name: Install kubernetes node.
  hosts: node
  gather_facts: true
  sudo: yes
  roles:
    - kubernetes/node
  tags:
    - node

- name: Install NFS to cloud.
  hosts: master
  gather_facts: true
  sudo: yes
  roles:
    - nfs
  tags:
    - nfs 

- name: Install the persistent volume.
  hosts: master
  gather_facts: true
  sudo: yes
  roles:
    - persistentvolume
  tags:
    - persistentvolume 
