---

- name: Install kubernetes master node.
  hosts: master
  gather_facts: true
  sudo: yes
  roles:
    - kubernetes/master 
  tags: 
    - master

- name: Install kubernetes node node.
  hosts: node
  gather_facts: true
  sudo: yes
  roles:
    - kubernetes/node
  tags:
    - node 
