---

- name: Create a psql pod
  kubernetes:
    api_endpoint: "{{ ansible_host }}:{{ api_servers_port }}"
    insecure: yes
    inline_data:
      apiVersion: v1
      kind: ReplicationController
      metadata:
        name: my-psql
      spec:
        replicas: 1
        template:
          metadata:
            labels:
              run: my-psql
          spec:
            volumes:
            - name: psql-persistent-storage
              hostPath:
                path: "/nfsshare/psql"
            containers:
            - name: my-psql
              image: "{{ master_IP }}:{{ registry_port }}/pgsql"
              resources:
                limits:
                  cpu: 1
                  memory: 512M
                requests:
                  cpu: 1
                  memory: 512M
              volumeMounts:
              - name: psql-persistent-storage
                mountPath: /var/lib/postgresql
              ports:
              - containerPort: "{{ psql_db_port }}"
                name: my-psql 
                protocol: TCP
              readinessProbe:
                tcpSocket:
                  port: "{{ psql_db_port }}"
                initialDelaySeconds: 5
                periodSeconds: 10
              livenessProbe:
                tcpSocket:
                  port: "{{ psql_db_port }}"
                initialDelaySeconds: 15
                periodSeconds: 20
    state: present
#---------------------------------------------------------------
