---
- name: Copy the virt7-docker-common-releas repository definition
  copy: src=virt7-docker-common-release.repo dest=/etc/yum.repos.d/virt7-docker-common-release.repo

- name: Install the latest version of kubernetes, etcd, flannel from the virt7-docker-common-release repo
  yum: name={{ item }} enablerepo=virt7-docker-common-release state=present
  with_items:
    - kubernetes
    - etcd
    - flannel

- name: Copy /etc/etcd/etcd.conf configuration
  copy: src=etcd.conf dest=/etc/etcd/etcd.conf
  notify: restart etcd

- name: Copy /etc/kubernetes/config configuration
  template:
        src=config
        dest=/etc/kubernetes/config
  notify: restart kube-controller-manager

- name: Copy /etc/kubernetes/apiserver configuration
  template:
        src=apiserver
        dest=/etc/kubernetes/apiserver
  notify: restart kube-apiserver

- name: Copy /etc/sysconfig/flanneld configuration
  template:
        src=flanneld
        dest=/etc/sysconfig/flanneld
  notify: restart flanneld

- name: Copy etcd.sh file and execute shell script.
  copy: src=etcd.sh dest=/tmp/etcd.sh mode=0755

# Temporary solution for setting network overlay configuration.
- name: Set network overlay configuration
  command: /bin/sh ./etcd.sh
  args:
    chdir: /tmp

- name: Make sure if services (etcd, kube-apiserver, kube-controller-manager, kube-scheduler, flanneld) are running
  systemd: state=started name={{ item }} enabled=yes
  with_items:
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - flanneld

# There are two temporary configuration for connection to the kubectl on local server. 
- name: Set default cluster
  command: kubectl config set-cluster default-cluster --server=http://{{kube_master}}:{{api_servers_port}}

- name: Set default connection to kubectl
  command: kubectl config set-context default-context --cluster=default-cluster --user=default-admin 

- name: Set default connection to kubectl
  command: kubectl config use-context default-context
