---
- name: Install the latest version of etcd, kubernetes-master, flannel 
  yum: name={{ item }} state=present
  with_items:
    - kubernetes-master
    - etcd
    - flannel

- name: Copy /etc/etcd/etcd.conf configuration
  copy: src=etcd.conf dest=/etc/etcd/etcd.conf
  notify: restart etcd

- name: Copy /etc/kubernetes/config configuration
  template:
        src=config
        dest=/etc/kubernetes/config
  notify: restart kube-controller-manager

- name: Copy /etc/kubernetes/apiserver configuration
  template:
        src=apiserver
        dest=/etc/kubernetes/apiserver
  notify: restart kube-apiserver

- name: Copy /etc/sysconfig/flanneld configuration
  template:
        src=flanneld
        dest=/etc/sysconfig/flanneld
  notify: restart flanneld

- name: Make sure if a services etcd is running
  systemd: state=started name=etcd enabled=yes

- name: Copy etcd.sh file and execute shell script.
  copy: src=flannel-config.json dest=/tmp/flannel-config.json mode=0755

- name: Set network overlay configuration
  command: /usr/bin/etcdctl set coreos.com/network/config < flannel-config.json
  args:
    chdir: /tmp

- name: Make sure if services (kube-apiserver, kube-controller-manager, kube-scheduler, flanneld) are running
  systemd: state=started name={{ item }} enabled=yes
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - flanneld
