---

# Environment variables.
env_name:				'dev'
env_sudo_user:				'sudouser'
project_name:				'abc'

# Docker variables.
registry_ip:				'127.0.0.1'
registry_port:				'5000'


# Kubernetes variables.
kube_master_ip:				'192.168.171.76'
kube_services_network_cidr:		'10.96.0.0/12'
kube_pods_network_cidr: 		'10.244.0.0/16'
kube_token: 				'6e8d50.820b14fae8b5a93d'
kube_admin_config:      	        '/etc/kubernetes/admin.conf'
