---


- name: Reset Kubernetes component.
  shell: "kubeadm reset"
  register: reset_cluster
  tags: configure

- name: Restart kubelet engine
  when: reset_cluster|succeeded
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
  register: started_docker
  tags: configure

- name: Join to Kubernetes cluster.
  when: started_docker|succeeded
  shell: |
    kubeadm join --skip-preflight-checks \
                 --token {{ kube_token }} \
                 {{ kube_master_ip }}:6443 \
                 --discovery-token-unsafe-skip-ca-verification  
  register: join_cluster
  tags: configure

- name: Enable and restart kubelet engine
  when: join_cluster|succeeded
  systemd:
    name: kubelet 
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet
  tags: configure
