---
- name: Copy the virt7-docker-common-releas repository definition
  copy: src=virt7-docker-common-release.repo dest=/etc/yum.repos.d/virt7-docker-common-release.repo

- name: Install the latest version of kubernetes, etcd, flannel from the virt7-docker-common-release repo
  yum: name={{ item }} enablerepo=virt7-docker-common-release state=present
  with_items:
    - kubernetes
    - etcd
    - flannel

- name: Copy kubelet configuration
  template: 
        src=kubelet
        dest=/etc/kubernetes/kubelet
  notify: restart kubelet

- name: Copy flanneld configuration 
  copy: src=flanneld dest=/etc/sysconfig/flanneld
  notify: restart flanneld

- name: Make sure if services are running
  systemd: state=started name={{ item }} enabled=yes
  with_items:
    - kube-proxy
    - kubelet
    - flanneld
    - docker
