---

- name: Install Kubernetes packages.
  include_tasks: pkg.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version > '6'

- name: Disable system swap.
  shell: "swapoff -a"
  tags: configure

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
  tags: configure

- name: Copy kubeadm conf to drop-in directory.
  template: 
    src: 20-extra-args.conf.j2 
    dest: /etc/systemd/system/kubelet.service.d/20-extra-args.conf
  notify: restart kubelet
  tags: configure
