apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    k8s-app: nginx
spec:
  ports:
  - port: {{ nginx_container_web_port }}
    protocol: TCP
  selector:
    k8s-app: nginx
  externalIPs:
  - {{ kube_node1_ip }}
