---
- name: Install the latest version of kubernetes-node, docker, flannel 
  yum: name={{ item }} state=present
  with_items:
    - kubernetes-node
    - docker
    - flannel

- name: Copy kubelet configuration
  template: 
        src=kubelet
        dest=/etc/kubernetes/kubelet
  notify: restart kubelet

- name: Copy a kubelet config file configuration
  template: 
        src=config
        dest=/etc/kubernetes/config
  notify: restart kubelet

- name: Copy a daemon.json file for docker
  template:
        src=daemon.json
        dest=/etc/docker/daemon.json
  notify: restart docker

- name: Copy docker configuration
  copy: src=docker dest=/etc/sysconfig/docker
  notify: restart docker

- name: Copy flanneld configuration 
  copy: src=flanneld dest=/etc/sysconfig/flanneld
  notify: restart flanneld

- name: Make sure if services are running
  systemd: state=started name={{ item }} enabled=yes
  with_items:
    - docker
    - flanneld
    - kubelet
    - kube-proxy
