---

- name: Set default cluster
  shell: kubectl config set-cluster default-cluster --server=http://{{ ansible_host }}:8080

- name: Set default connection to kubectl
  command: kubectl config set-context default-context --cluster=default-cluster --user=default-admin 

- name: Set default connection to kubectl
  command: kubectl config use-context default-context
