--- 

- name: Reset Kubernetes component.
  shell: "kubeadm reset"
  register: reset_cluster

- name: Restart docker engine.
  when: reset_cluster|succeeded
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_docker

- name: Init Kubernetes cluster
  when: started_docker|succeeded
  shell: |
    kubeadm init --service-cidr {{ kube_services_network_cidr }} \
                 --kubernetes-version {{ kube_version }} \
                 --pod-network-cidr {{ kube_pods_network_cidr }} \
                 --apiserver-advertise-address {{ kube_master_ip }} \
                 --token {{ kube_token }} 
  register: init_cluster

- name: Create Kubernetes config directory
  when: init_cluster|succeeded
  file: 
    path: /root/.kube/ 
    state: directory

- name: Copy admin.conf to Home directory
  when: init_cluster|succeeded
  copy:
    src: "{{ kube_admin_config }}"
    dest: "/root/.kube/config"
    owner: root
    group: root
    mode: 0755
    remote_src: True

- name: Enable and restart kubelet engine
  when: init_cluster|succeeded
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet

- name: Setup the flannel configuration.
  when: started_kubelet|succeeded
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
