---

- name: Create a registry-ui service
  kubernetes:
    api_endpoint: "{{ ansible_host }}:{{ api_servers_port }}"
    insecure: yes
    inline_data:
      apiVersion: v1
      kind: Service
      metadata:
        name: my-registry-ui
        labels:
          run: my-registry-ui
      spec:
        ports:
        - port: "{{ ui_registry_port_def }}"
          protocol: TCP
        clusterIP: "{{ ui_registry_port_ip }}"
        selector:
          run: my-registry-ui
    state: absent 
#---------------------------------------------------------------

- name: Create a registry-ui service
  kubernetes:
    api_endpoint: "{{ ansible_host }}:{{ api_servers_port }}"
    insecure: yes
    inline_data:
      apiVersion: v1
      kind: Service
      metadata:
        name: my-registry-ui
        labels:
          run: my-registry-ui
      spec:
        ports:
        - port: "{{ ui_registry_port_def }}" 
          protocol: TCP
        clusterIP: "{{ ui_registry_port_ip }}"
        selector:
          run: my-registry-ui
    state: present
#---------------------------------------------------------------
