apiVersion: v1
kind: ReplicationController
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      volumes:
      - name: registry-persistent-storage
        hostPath:
          path: "/nfsshare/registry"
      containers:
      - name:  registry
        image: docker.io/registry:2
        resources:
          limits:
            cpu: 1
            memory: 256M
          requests:
            cpu: 1
            memory: 256M
        volumeMounts:
        - name: registry-persistent-storage
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
