---

- name: Install commons packages.
  include_tasks: pkg.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version > '6'

- name: Disable firewall.
  service:
    name: firewalld
    state: stopped
    enabled: no
  tags: configure

- name: Disable SELinux.
  selinux:
    state: disabled
  tags: configure

- name: Ensure hostname set.
  hostname:
    name: "{{ inventory_hostname }}"
  tags: configure

- name: Install bashrc for login user.
  template:
    src: "bashrc.j2"
    dest: "/home/{{ env_sudo_user }}/.bashrc"
  tags: configure

- name: Set ip forwarding on in /proc and in the sysctl file and reload if necessary.
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  tags: configure

- name: Include UTC configuration.
  include_tasks: ntp.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version > '6'

- name: Include SSHD configuration.
  include_tasks: sshd.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version > '6'

- name: Include MOTD configuration.
  include_tasks: motd.yml
