---
- name: Install libselinux-python
  yum: 
    name: libselinux-python 
    state: present

- name: Disable firewalld
  service: 
    name: firewalld 
    state: stopped 
    enabled: no 

- name: Disable SELinux
  selinux: 
    state: disabled 

- name: Install docker-python, mc, vim, wget, git, ntp
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    - epel-release
    - docker-python
    - net-tools
    - mc
    - vim
    - wget
    - git
    - ntp
    - telnet
    - mtr

- name: Copy the hosts file
  template:
    src: hosts
    dest: /etc/hosts

- name: Ensure hostname set
  hostname: 
    name: "{{ inventory_hostname }}"

- name: Set ip forwarding on in /proc and in the sysctl file and reload if necessary
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Make sure if a services ntp is running
  systemd: 
    state: started 
    name: ntpd 
    enabled: yes

