---
- name: Install nfs-utils
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    - nfs-utils

- name: Create mountable dir
  file: 
    path: /nfsshare 
    state: directory 
    mode: 766 

- name: Make sure if services are running
  systemd: 
    state: started 
    name: "{{ item }}" 
    enabled: yes
  with_items:
    - rpcbind
    - nfs-server
    - nfs-lock
    - nfs-idmap

- name: Set a mountpoint  
  mount: 
    name: /nfsshare 
    src: "{{server_nfs_hostname}}:/var/nfsshare" 
    fstype: nfs 
    state: mounted
