---
- name: Install the zabbix zabbix repository from a remote repo
  yum: 
    name: http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm 
    state: present

- name: Install the latest version of zabbix server.
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    - zabbix-server-pgsql
    - zabbix-web-pgsql
    - postgresql

- name: Copy a zabbix_server.conf file to server
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
  notify: restart zabbix-server

- name: Copy a httpd.conf file to server
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify: restart httpd 

- name: Copy a zabbix.conf file to server
  template:
    src: zabbix.conf.j2
    dest: /etc/httpd/conf.d/zabbix.conf
  notify: restart httpd

- name: Copy a zabbix.conf.php file to server
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
  notify: restart zabbix-server

#########################################################################
# - We need this service only for first PSQL configuration.
# - Pay attention if PSQL be disabled, 
# - this option will not be able to work.
#########################################################################
#- name: Populate PSQL database
#  shell: |
#        export PGPASSWORD={{ zb_db_password }} && 
#        zcat /usr/share/doc/zabbix-server-pgsql-*/create.sql.gz | psql \ 
#        -h {{ zb_db_server }} \
#        -U {{ zb_db_user }} \
#        -d {{ zb_db_name }}
#########################################################################

- name: Make sure if a service zabbix-agent is running
  systemd: 
    state: started 
    name: "{{ item }}" 
    enabled: yes
  with_items:
    - zabbix-server
    - httpd

